"use client";
import { useRef } from "react";
import styles from "./page.module.css";
import Head from "next/head";
import Header from "../components/header/header";
import Hero from "../components/hero/hero";
import Services from "../components/services/services";
import Recomendations from "../components/recomendations/recomendations";
import BannerMeet from "../components/banner-meet/banner-meet";
import FrecuentQuestions from "../components/frecuent-questions/frecuent-questions";
import CallToAction from "../components/call-to-action/call-to-action";
import Footer from "../components/footer/footer";

export default function Home() {

  const goUp = useRef(null);

  return (
    <>
      <Head>
        <title>home page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header goUp={goUp} />
        <Hero />
        <Services />
        <BannerMeet />
        <Recomendations />
        <FrecuentQuestions />
        <CallToAction />
        <Footer goUp={goUp} />
      </main>
    </>
  );
}
